#!/usr/bin/env hellish
# ============================================================================ #
#  born2root — reach the groot / track-binocle apps from the HOST, over HTTPS  #
# ============================================================================ #
#
# THE PROBLEM (two separate failures that look like one certificate warning)
#
#   1. The transport is a dead end. groot's docker-compose publishes every app
#      port as "${TRACK_BINOCLE_BIND_ADDR:-127.0.0.1}:<port>:<port>", so inside
#      the guest nginx listens on 127.0.0.1:3001 and nothing else:
#
#        guest$ ss -ltn | grep 3001   →  LISTEN 127.0.0.1:3001
#        guest$ ss -ltn | grep 4242   →  LISTEN 0.0.0.0:4242     (sshd, works)
#
#      QEMU's user-mode NAT forwards a host port to the GUEST NIC (10.0.2.15),
#      never to the guest's loopback, so `hostfwd=tcp:127.0.0.1:3001-:3001` can
#      never connect. slirp still accepts the host-side TCP connection first and
#      only then discovers it has nowhere to send it, which is why the symptom
#      is not "connection refused" but a TLS handshake that dies mid-way:
#
#        host$ curl https://localhost:3001/
#        error:0A000126:SSL routines::unexpected eof while reading
#
#      The same URL answers 200 inside the guest. An SSH LocalForward works
#      because sshd is in the guest and dials 127.0.0.1:3001 from there — it is
#      the only transport that reaches a loopback-bound service, and it needs
#      no change to groot and no `ufw allow`. So: tunnel, do not re-bind.
#
#   2. The trust anchor was stale. apps/grobase/certs is regenerated by
#      `make certs`, and the copy sitting on the host was from the run before:
#
#        host CA  A5:59:98:D6:…   guest CA  3C:A4:68:36:…
#
#      Both browsers were correctly configured and still warned, because they
#      trusted a CA that no longer signs anything. Hence the delete-then-add
#      below: re-running this script after `make certs` must replace the entry,
#      not leave two under the same nickname.
#
# WHY NSS AND NOT /usr/local/share/ca-certificates
#   There is no root on a 42 seat, so the system store is unreachable — and it
#   would not help anyway: Firefox and Chrome both read NSS databases, not the
#   system store. certutil lives in libnss3-tools, which cannot be installed
#   here either, so it is unpacked into ~/.cache as an ordinary user exactly as
#   inception_host_access.sh does.
#
# Run:   make groot            (map + tunnel + CA trust + per-port verify)
#        make groot_map        (just print the app ↔ port map)
# Undo:  make groot_undo       (drop the tunnel and the CA, keep everything else)
# ============================================================================ #

# File-level, with the reason, rather than a disable on each of a dozen lines:
#   SC2059  the colour constants are part of the format string, house style in
#           every other script here.
#   SC2086  $SSH_OPTS is an option list that MUST word-split.
#   SC2029  the guest-side paths in the remote commands are expanded on the
#           host on purpose — that is where GROOT_DIR is known.
# shellcheck disable=SC2059,SC2086,SC2029
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/../.." && pwd)"

# The guest is reached through the alias `make all` wrote into ~/.ssh/config.
SSH_HOST="${GROOT_SSH_HOST:-b2b}"
# Path of the groot checkout inside the guest, relative to the guest's $HOME.
GROOT_DIR="${GROOT_DIR:-groot}"
NGINX_CONF="$GROOT_DIR/infrastructure/tls/nginx.conf"
GUEST_CA="$GROOT_DIR/apps/grobase/certs/track-binocle-local-ca.pem"

# Same nickname groot's own infrastructure/makes/certs.mk uses, so this script
# and `make certs-trust` inside the guest can never leave two rival entries.
CA_NICKNAME="Track Binocle Local CA"
# Nicknames earlier runs used for the same certificate; deleted before adding so
# a store touched by an older tool does not keep a stale anchor alive.
LEGACY_NICKNAMES="Track Binocle Local Development CA"

STATE_DIR="$HOME/.local/share/born2root"
TUNNEL_PID="$STATE_DIR/groot-tunnel.pid"
CA_FILE="$STATE_DIR/track-binocle-local-ca.pem"
CERTUTIL_CACHE="$HOME/.cache/born2root/nss"

# ~/.ssh/config may carry LocalForward lines for other projects whose ports are
# already taken. ExitOnForwardFailure would make the whole tunnel refuse to come
# up because of one of those, so it stays off and each port is verified instead.
SSH_OPTS="-o BatchMode=yes -o ConnectTimeout=10 -o ExitOnForwardFailure=no"

C_RESET=$'\033[0m'
C_BOLD=$'\033[1m'
C_GREEN=$'\033[32m'
C_YELLOW=$'\033[33m'
C_BLUE=$'\033[34m'
C_DIM=$'\033[2m'

ok() { printf "  ${C_GREEN}✓${C_RESET} %s\n" "$*"; }
warn() { printf "  ${C_YELLOW}⚠${C_RESET}  %s\n" "$*"; }
info() { printf "  ${C_BLUE}▶${C_RESET} %s\n" "$*"; }

ACTION=configure
case "${1:-}" in
--undo) ACTION=undo ;;
--map) ACTION=map ;;
esac

# ── The app ↔ port map ──────────────────────────────────────────────────────
# Read out of the guest's own nginx.conf rather than copied here: groot adds a
# `listen <port> ssl` + `set $track_binocle_upstream <service>:<port>` pair per
# app, so a new app appears in this map the moment it is proxied, and a map that
# disagrees with the running stack is impossible.
discover_ports() {
    ssh $SSH_OPTS "$SSH_HOST" "awk '
        /listen [0-9]+ ssl/ { port = \$2 }
        /track_binocle_upstream [a-z]/ {
            if (port != \"\") {
                u = \$3; sub(/;\$/, \"\", u)
                print port \"\t\" u
                port = \"\"
            }
        }' \"$NGINX_CONF\"" 2>/dev/null
}

# nginx.conf carries a server block for every app that COULD be fronted, but a
# port only exists on the guest when local-https-proxy publishes it, and the two
# sets do drift: on 2026-09-18 blocks for kong :8001 and vault :8200 had no
# mapping, while host :8000 was Kong's own PLAIN http listener, so a tunnel
# there would have handed the host an https:// URL that could only ever fail.
# Hence the intersection: an unpublished block is listed apart, never tunnelled.
published_ports() {
    ssh $SSH_OPTS "$SSH_HOST" \
        "docker port track-binocle-local-https-proxy-1 2>/dev/null | sed 's/.*://'" 2>/dev/null
}

# Human labels for the upstream service names. Only cosmetic: an upstream with
# no entry here still appears in the map, under its own service name.
describe_upstream() {
    case "${1%%:*}" in
    osionos-app) printf 'osionos — Notion-style workspace & block editor' ;;
    osionos-bridge) printf 'osionos bridge — persistence / gateway API' ;;
    mail) printf 'mail — webmail UI' ;;
    mail-bridge) printf 'mail bridge — mail backend API' ;;
    calendar) printf 'calendar — calendar UI' ;;
    calendar-bridge) printf 'calendar bridge — calendar backend API' ;;
    opposite-osiris-web) printf 'website — opposite-osiris (Astro)' ;;
    auth-gateway) printf 'auth gateway — login / session issuing' ;;
    kong | mini-baas-kong) printf 'grobase BaaS — Kong data plane (TLS edge)' ;;
    vault) printf 'vault — secrets (optional, often not running)' ;;
    *) printf '%s' "${1%%:*}" ;;
    esac
}

print_map() {
    local port upstream
    printf "\n  ${C_BOLD}%-7s %-26s %s${C_RESET}\n" "PORT" "UPSTREAM" "APP"
    while IFS=$'\t' read -r port upstream; do
        [ -n "$port" ] || continue
        printf "  %-7s %-26s %s\n" "$port" "$upstream" "$(describe_upstream "$upstream")"
    done <<<"$PORT_MAP"
    printf "\n  ${C_DIM}Every port above is TLS, terminated by the same local-https-proxy${C_RESET}\n"
    printf "  ${C_DIM}container with one certificate (CN=localhost), so trusting the one${C_RESET}\n"
    printf "  ${C_DIM}CA below makes all of them green at once.${C_RESET}\n"
    [ -n "$PORT_UNPUBLISHED" ] || return 0
    printf "\n  ${C_DIM}Configured in nginx.conf but not published by the proxy, so not${C_RESET}\n"
    printf "  ${C_DIM}HTTPS and not tunnelled:${C_RESET}\n"
    while IFS=$'\t' read -r port upstream; do
        [ -n "$port" ] || continue
        printf "  ${C_DIM}  %-7s %-26s %s${C_RESET}\n" "$port" "$upstream" "$(describe_upstream "$upstream")"
    done <<<"$PORT_UNPUBLISHED"
}

# ── Free the host ports the dead QEMU forwards are squatting on ─────────────
# qemu_vm.sh created hostfwd rules for these ports at boot. They can never carry
# traffic (see the header) but they do hold the host port, so the SSH tunnel
# cannot bind it. hostfwd_remove is a runtime monitor command: it drops the rule
# without touching the VM, and the next `make qemu_start` recreates it anyway.
VM_DIR=""
resolve_vm_dir() {
    local vm_name vm_path
    vm_name="${VM_NAME:-debian}"
    vm_path="${VM_PATH:-$REPO_ROOT/disk_images}"
    [ -S "$vm_path/$vm_name/monitor.sock" ] && VM_DIR="$vm_path/$vm_name"
}

mon() {
    [ -n "$VM_DIR" ] || return 1
    python3 - "$VM_DIR/monitor.sock" "$1" <<'PYEOF' 2>/dev/null
import socket, sys, time
sock, cmd = sys.argv[1], sys.argv[2]
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.settimeout(5)
s.connect(sock)
time.sleep(0.2)
try: s.recv(65536)
except Exception: pass
s.sendall((cmd + "\n").encode())
out = b""; t0 = time.time()
while time.time() - t0 < 4:
    try: chunk = s.recv(65536)
    except Exception: break
    if not chunk: break
    out += chunk
    if out.rstrip().endswith(b"(qemu)"): break
sys.stdout.write(out.decode(errors="replace"))
s.close()
PYEOF
}

# Only a rule whose host port we are about to claim is removed, and only when
# the host port is actually held by QEMU — never a port some other program owns.
free_qemu_forwards() {
    local port n=0
    resolve_vm_dir
    [ -n "$VM_DIR" ] || return 0
    while IFS=$'\t' read -r port _; do
        [ -n "$port" ] || continue
        ss -ltnp 2>/dev/null | grep -q "127.0.0.1:${port} .*qemu" || continue
        mon "hostfwd_remove tcp:127.0.0.1:${port}" >/dev/null 2>&1 && n=$((n + 1))
    done <<<"$PORT_MAP"
    [ "$n" -gt 0 ] && ok "released $n unusable QEMU forward(s) so the tunnel can bind them"
    return 0
}

# ── The tunnel ──────────────────────────────────────────────────────────────
tunnel_alive() {
    [ -r "$TUNNEL_PID" ] || return 1
    local pid
    pid=$(cat "$TUNNEL_PID" 2>/dev/null)
    [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null
}

stop_tunnel() {
    tunnel_alive || {
        rm -f "$TUNNEL_PID"
        return 0
    }
    kill "$(cat "$TUNNEL_PID")" 2>/dev/null
    rm -f "$TUNNEL_PID"
}

start_tunnel() {
    local port forwards="" pid
    while IFS=$'\t' read -r port _; do
        [ -n "$port" ] || continue
        forwards="$forwards -L ${port}:127.0.0.1:${port}"
    done <<<"$PORT_MAP"
    [ -n "$forwards" ] || return 1

    mkdir -p "$STATE_DIR"
    stop_tunnel
    # -f backgrounds only once authentication and the forwards are set up, so a
    # successful return already means the listeners exist (or failed loudly).
    # shellcheck disable=SC2086
    ssh -f -N $SSH_OPTS $forwards "$SSH_HOST" 2>/dev/null
    pid=$(pgrep -f "ssh -f -N .*-L .*${SSH_HOST}\$" 2>/dev/null | tail -1)
    [ -n "$pid" ] || return 1
    printf '%s\n' "$pid" >"$TUNNEL_PID"
    return 0
}

# ── The CA ──────────────────────────────────────────────────────────────────
fetch_ca() {
    mkdir -p "$STATE_DIR"
    local tmp
    tmp=$(mktemp) || return 1
    if ssh $SSH_OPTS "$SSH_HOST" "cat \"$GUEST_CA\"" >"$tmp" 2>/dev/null &&
        grep -q "BEGIN CERTIFICATE" "$tmp"; then
        mv "$tmp" "$CA_FILE"
        return 0
    fi
    rm -f "$tmp"
    return 1
}

# libnss3-tools needs root to install but not to unpack, and the unpacked
# certutil links against the libnss3 the browsers already ship.
find_certutil() {
    local c
    for c in certutil "$HOME/.local/bin/certutil" "$CERTUTIL_CACHE/usr/bin/certutil"; do
        if command -v "$c" >/dev/null 2>&1; then
            command -v "$c"
            return 0
        fi
        [ -x "$c" ] && {
            printf '%s' "$c"
            return 0
        }
    done
    command -v apt-get >/dev/null 2>&1 && command -v dpkg-deb >/dev/null 2>&1 || return 1
    local dl deb
    dl=$(mktemp -d) || return 1
    if (cd "$dl" && timeout 120 apt-get download libnss3-tools >/dev/null 2>&1); then
        deb=$(find "$dl" -name 'libnss3-tools_*.deb' | head -1)
        [ -n "$deb" ] && {
            mkdir -p "$CERTUTIL_CACHE"
            dpkg-deb -x "$deb" "$CERTUTIL_CACHE" >/dev/null 2>&1
        }
    fi
    rm -rf "$dl"
    [ -x "$CERTUTIL_CACHE/usr/bin/certutil" ] || return 1
    printf '%s' "$CERTUTIL_CACHE/usr/bin/certutil"
}

# Every NSS database a browser on this host might read. find, not a glob: the
# snap and flatpak layouts are frequently absent and an unmatched glob aborts
# the script under hellish.
nss_stores() {
    [ -d "$HOME/.pki/nssdb" ] && printf '%s\n' "$HOME/.pki/nssdb"
    local root
    for root in "$HOME/.mozilla/firefox" \
        "$HOME/snap/firefox/common/.mozilla/firefox" \
        "$HOME/.var/app/org.mozilla.firefox/.mozilla/firefox" \
        "$HOME/snap/chromium/current/.pki" \
        "$HOME/snap/chromium/common/.pki"; do
        [ -d "$root" ] || continue
        find "$root" -maxdepth 2 -name cert9.db -printf '%h\n' 2>/dev/null
    done
}

install_ca() {
    local cu store n=0
    cu=$(find_certutil) || {
        warn "no certutil — the browsers will keep warning about the certificate"
        return 1
    }
    while read -r store; do
        [ -n "$store" ] || continue
        local nick
        for nick in "$CA_NICKNAME" $LEGACY_NICKNAMES; do
            "$cu" -D -n "$nick" -d "sql:$store" >/dev/null 2>&1
        done
        "$cu" -A -n "$CA_NICKNAME" -t "C,," -d "sql:$store" -i "$CA_FILE" >/dev/null 2>&1 &&
            n=$((n + 1))
    done <<<"$(nss_stores)"
    if [ "$n" -gt 0 ]; then
        ok "CA trusted in $n NSS store(s) — Firefox and Chrome"
        return 0
    fi
    warn "no NSS store found — launch Firefox/Chrome once, then re-run"
    return 1
}

remove_ca() {
    local cu store nick
    cu=$(find_certutil 2>/dev/null) || return 0
    while read -r store; do
        [ -n "$store" ] || continue
        for nick in "$CA_NICKNAME" $LEGACY_NICKNAMES; do
            "$cu" -D -n "$nick" -d "sql:$store" >/dev/null 2>&1
        done
    done <<<"$(nss_stores)"
    ok "CA removed from every NSS store"
}

# ── Verify ──────────────────────────────────────────────────────────────────
# curl with --cacert is the same check the browser makes, so a green line here
# means the browser will not warn. Anything else is reported per port rather
# than as one "it works", because a single app being down is the common case.
verify_ports() {
    local port upstream code verify down=0
    printf "\n  ${C_BOLD}%-7s %-8s %s${C_RESET}\n" "PORT" "HTTP" "URL"
    while IFS=$'\t' read -r port upstream; do
        [ -n "$port" ] || continue
        read -r code verify <<<"$(timeout 8 curl -s -o /dev/null \
            -w '%{http_code} %{ssl_verify_result}' \
            --cacert "$CA_FILE" "https://localhost:${port}/" 2>/dev/null)"
        if [ "${verify:-1}" = "0" ] && [ "${code:-000}" != "000" ]; then
            printf "  ${C_GREEN}✓${C_RESET} %-5s %-8s https://localhost:%s/\n" \
                "$port" "$code" "$port"
        else
            printf "  ${C_YELLOW}⚠${C_RESET} %-5s %-8s https://localhost:%s/  ${C_DIM}(%s)${C_RESET}\n" \
                "$port" "${code:-000}" "$port" "${upstream%%:*} not running?"
            down=$((down + 1))
        fi
    done <<<"$PORT_MAP"
    [ "$down" -gt 0 ] && printf "\n  ${C_DIM}A ⚠ line is an app that is down, not a certificate problem:${C_RESET}\n  ${C_DIM}the TLS front door is one container, and it answered for the rest.${C_RESET}\n"
    return 0
}

# ── Main ────────────────────────────────────────────────────────────────────
printf "\n${C_BOLD}groot host access${C_RESET} ${C_DIM}(guest: %s)${C_RESET}\n" "$SSH_HOST"

if [ "$ACTION" = "undo" ]; then
    stop_tunnel
    ok "tunnel closed"
    remove_ca
    printf "\n  ${C_DIM}QEMU's own forwards are recreated on the next VM start.${C_RESET}\n\n"
    exit 0
fi

ALL_PORTS=$(discover_ports)
if [ -z "$ALL_PORTS" ]; then
    printf "\n  Could not read %s over ssh %s.\n" "$NGINX_CONF" "$SSH_HOST"
    printf "  Is the VM up (make status) and is groot checked out at ~/%s ?\n\n" "$GROOT_DIR"
    exit 1
fi
PUBLISHED=$(published_ports)
PORT_MAP=$(printf '%s\n' "$ALL_PORTS" |
    awk -v pub="$PUBLISHED" 'BEGIN { split(pub, a, "\n"); for (i in a) p[a[i]] = 1 }
        $1 in p')
PORT_UNPUBLISHED=$(printf '%s\n' "$ALL_PORTS" |
    awk -v pub="$PUBLISHED" 'BEGIN { split(pub, a, "\n"); for (i in a) p[a[i]] = 1 }
        !($1 in p)')
# No `docker port` output at all (docker down, or a renamed container) is not a
# reason to tunnel nothing: fall back to every server block rather than refuse.
[ -n "$PORT_MAP" ] || {
    PORT_MAP="$ALL_PORTS"
    PORT_UNPUBLISHED=""
    warn "could not read the proxy's published ports — using every nginx server block"
}
ok "$(printf '%s' "$PORT_MAP" | grep -c .) HTTPS app port(s) published in the guest"

print_map
[ "$ACTION" = "map" ] && {
    printf "\n"
    exit 0
}

free_qemu_forwards
if start_tunnel; then
    ok "SSH tunnel up (pid $(cat "$TUNNEL_PID"))"
else
    warn "tunnel did not start — every port below will fail"
fi

if fetch_ca; then
    ok "CA fetched: $(openssl x509 -in "$CA_FILE" -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2 | cut -c1-23)…"
    install_ca
else
    warn "no CA in the guest at ~/$GUEST_CA — run 'make certs' there first"
fi

verify_ports

printf "\n  ${C_BOLD}Restart Firefox completely${C_RESET} (every window) before testing: NSS is\n"
printf "  ${C_DIM}read at startup, so a running Firefox keeps the old anchor.${C_RESET}\n"
printf "  ${C_DIM}Re-run this after 'make certs' in the guest — the CA changes.${C_RESET}\n\n"
